### ISSUE TITLE
additional information for the plex api

### ISSUE THREAD

**Issue by ADRFranklin** [LukeHagar/plex-api-spec#14]
Hi,

I am currently working on a project that makes use of the plex apis and am currently generating a http client from this library, and just wanted to pop in and give some additional information based on some data I have found myself. 

So just off the top of my head for what I am currently doing, I can think of 2 additions that change or add to the data you currently have. 

1. One being `includeElements` set to `Stream` for the endpoint `/library/metadata/<ratingKey>/children` which adds the `Media` section to the data, which is not currently present in your response.

2. Another new endpoint you don't have yet is `/statistics/resources` which allows returning resources like cpu/ram stats. What I have for this one is: https://github.com/petio-team/petio/blob/dev/server/src/services/plex/serverInfo.ts

3. Same as number 2, though using bandwidth endpoint: `/statistics/bandwidth` which returns bandwidth data. What I have for this one is: https://github.com/petio-team/petio/blob/dev/server/src/services/plex/bandwidth.ts

Let me know if you want me to create a PR for this or not, hope this helps a bit. I can continue to make issues and prs about other endpoints I found, if this is acceptable.

**Comment by ADRFranklin** [comment]
4. `includeGuids` can be added to `/library/all` and `/library/sections/<sectionId>/<tag>` which adds `Guid` array containing different provider ids such as `tmdb`, `imdb` and `tvdb`.

**Comment by LukeHagar** [comment]
Apologies for not responding here sooner.

Feel free to submit any and all PRs you can!

If you have any questions please let me know.
