### ISSUE TITLE
Watchlist spec

### ISSUE THREAD

**Issue by shawncatz** [LukeHagar/plex-api-spec#16]
Wondering if there's plans to add support for the watchlist-related api calls... or if you're open to me adding them.

Specifically looking for user watchlists (`/library/sections/watchlist/all`) with the user's token on the `https://metadata.provider.plex.tv` api

**Comment by LukeHagar** [comment]
Hey @shawncatz!

You are more than welcome to add the endpoints, and I plan to support anything and everything I can with Plex, time is just a factor.

If you want to take a crack at it just let me know if any issues or questions you have, I also have a discord server for these open source Plex development conversations. 

I'll get the link for that posted here when I get hands on a computer.

**Comment by shawncatz** [comment]
Awesome, I'll take a stab at it and let you know

**Comment by shawncatz** [comment]
opened #18
