### ISSUE TITLE
Unable to clone, unsupported path.

### ISSUE THREAD

**Issue by sbeaudoin** [LukeHagar/plex-api-spec#54]
Not a git expert, but the following command gives the following error, making me suspect the possibly unsuported space at the end of PULL_REQUEST_TEMPLATE before the slash.

`git clone https://github.com/LukeHagar/plex-api-spec.git .`

`error: invalid path '.github/PULL_REQUEST_TEMPLATE /default.md'`

**Comment by JasonLandbridge** [comment]
@sbeaudoin Thanks for the report! Can you try again?
