### ISSUE TITLE
type parameter required when getting playlist items

### ISSUE THREAD

**Issue by robatosan** [LukeHagar/plex-api-spec#65]
I was trying to get the playlist items with `/playlists/:id/items`. 

Unfortunately the `type` parameter is **required** and on top of that limited to only four types ( 1 = movie 2 = show 3 = season 4 = episode).

This makes it impossible to get e.g. audio items (type 8) by either specifying type 8 or leaving out the type parameter entirely.

**Comment by LukeHagar** [comment]
Hey is this requirement/limitation something you are seeing with the API or an SDK?

**Comment by robatosan** [comment]
> Wild guess, but can you pass in `type: 0`? This should be a workaround. The type is in most cases required but adding audio, and other types should be the larger fix here. Do you happen to know what other types there are? They do seem to be global, such as `audio = type 8`

Not sure what type: 0 means , but it's not defined as a [PlexMediaType](https://github.com/LukeHagar/plex-api-spec/blob/main/src/models/common/PlexMediaType.yaml) and therefore no choice in any of the SDKs I mentioned. 

Also when I try it in a request on an audio playlist (`/playlists/:id/items?type=0`) I get an empty playlist as a result.
Only when I either specify type 8 or no type at all, I can retrieve the items.
I found this out by trying around, so I have no idea what other types there are :)

**Comment by JasonLandbridge** [comment]
@robatosan I have added Audio to the mediatype, it might take a moment for it to be propegated to the various SDK's
